apiVersion: apps/v1
kind: Deployment
metadata:
  name: register-api
  labels:
    app: register-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: register-api
  template:
    metadata:
      labels:
        app: register-api
    spec:
      containers:
      - name: register-api
        image: gabriel-llanir/register-api:latest
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: jwt-secret
        - name: RSA_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: rsa-private-key
        - name: RSA_PUBLIC_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: rsa-public-key
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      imagePullSecrets:
      - name: regcred