apiVersion: apps/v1
kind: Deployment
metadata:
  name: update-consumer
  labels:
    app: update-consumer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: update-consumer
  template:
    metadata:
      labels:
        app: update-consumer
    spec:
      containers:
      - name: update-consumer
        image: insanexurow10/update-consumer:latest
        ports:
        - containerPort: 80
        envFrom:
          - configMapRef:
              name: mongo-config
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: jwt-secret
        - name: RSA_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: rsa-private-key
        - name: RSA_PUBLIC_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: rsa-public-key
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      imagePullSecrets:
      - name: regcred