name: CI / CD Pipeline

on:
  push:
    branches:
      - main
jobs:
  build_and_test:
    runs-on: ubuntu-latest

    env:
      Solution: ${{ vars.SOLUTION_PATH }}
      Main: ${{ vars.MAIN_PROJECT_PATH }}
      Test: ${{ vars.TEST_PROJECT_PATH }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.x'

    - name: Restore dependencies
      run: dotnet restore ${{ env.Solution }}

    - name: Build main project
      run: dotnet build ${{ env.Main }} --no-restore --configuration Release
      
    - name: Build test project
      run: dotnet build ${{ env.Test }} --no-restore --configuration Release

    - name: Run tests
      run: dotnet test ${{ env.Test }} --no-build --verbosity detailed --configuration Release