name: CI / CD Pipeline

on:
  push:
    branches:
      - main
jobs:
  build_and_test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017
        options: >
          --health-cmd "echo 'db.runCommand({ ping: 1 })' | mongo --quiet" 
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      Solution: ${{ vars.SOLUTION_PATH }}
      Main: ${{ vars.MAIN_PROJECT_PATH }}
      UnitTest: ${{ vars.UNIT_TEST_PROJECT_PATH }}
      IntegrationTest: ${{ vars.INTEGRATION_TEST_PROJECT_PATH }}
      TestDataBase: ${{ vars.TEST_DATABASE_URL }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.x'

    - name: Restore dependencies
      run: dotnet restore ${{ env.Solution }}

    - name: Build main project
      run: dotnet build ${{ env.Main }} --no-restore --configuration Release
      
    - name: Build Test projects
      run: |
        dotnet build ${{ env.UnitTest }} --no-restore --configuration Release
        dotnet build ${{ env.IntegrationTest }} --no-restore --configuration Release

    - name: Run Unit Tests
      run: dotnet test ${{ env.UnitTest }} --no-build --verbosity normal --configuration Release

    - name: Run Integration Tests
      run: dotnet test ${{ env.IntegrationTest }} --no-build --verbosity normal --configuration Release



