name: CI / CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    env:
      Kube: ${{ secrets.KUBE_CONFIG }}
      Docker_User: ${{ secrets.DOCKER_USERNAME }}
      Docker_Password: ${{ secrets.DOCKER_PASSWORD }}
      JWT_Secret: ${{ secrets.JWT_SECRET }}
      RSA_Private: ${{ secrets.RSA_PRIVATE_KEY }}
      RSA_Public: ${{ vars.RSA_PUBLIC_KEY }}
      Solution: ${{ vars.SOLUTION_PATH }}
      Gateway: ${{ vars.GATEWAY_API_PATH }}
      Consulta: ${{ vars.CONSULTA_API_PATH }}
      Register: ${{ vars.REGISTER_CONSUMER_PATH }}
      Update: ${{ vars.UPDATE_CONSUMER_PATH }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'

    - name: Restore dependencies
      run: dotnet restore ${{ env.Solution }}

    - name: Build API projects
      run: |
        dotnet build ${{ env.Gateway }}/Gateway.csproj --no-restore --configuration Release
        dotnet build ${{ env.Consulta }}/Consulta.csproj --no-restore --configuration Release

    - name: Build Consumer projects
      run: |
        dotnet build ${{ env.Register }}/RegisterConsumer.csproj --no-restore --configuration Release
        dotnet build ${{ env.Update }}/UpdateConsumer.csproj --no-restore --configuration Release

    - name: Build Docker images
      run: |
        docker build -t gabriel-llanir/gateway-api:latest -f ${{ env.Gateway }}/Dockerfile .
        docker build -t gabriel-llanir/consulta-api:latest -f ${{ env.Consulta }}/Dockerfile .
        docker build -t gabriel-llanir/register-consumer:latest -f ${{ env.Register }}/Dockerfile .
        docker build -t gabriel-llanir/update-consumer:latest -f ${{ env.Update }}/Dockerfile .

    - name: Log in to Docker Registry
      run: echo "${{ env.Docker_Password }}" | docker login -u "${{ env.Docker_User }}" --password-stdin

    - name: Push Docker images
      run: |
        docker push gabriel-llanir/gateway-api:latest
        docker push gabriel-llanir/consulta-api:latest
        docker push gabriel-llanir/register-consumer:latest
        docker push gabriel-llanir/update-consumer:latest

    - name: Configure Kubernetes
      run: |
        echo "${{ env.Kube }}" > kubeconfig.yaml
        export KUBECONFIG=kubeconfig.yaml

    - name: Verify Kubernetes access
      run: |
        kubectl get nodes

    - name: Validate Kubernetes manifests
      run: |
        kubectl apply --dry-run=client -f kubernetes/gateway-deployment.yaml
        kubectl apply --dry-run=client -f kubernetes/consulta-deployment.yaml
        kubectl apply --dry-run=client -f kubernetes/register-consumer-deployment.yaml
        kubectl apply --dry-run=client -f kubernetes/update-consumer-deployment.yaml

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f kubernetes/gateway-deployment.yaml
        kubectl apply -f kubernetes/consulta-deployment.yaml
        kubectl apply -f kubernetes/register-consumer-deployment.yaml
        kubectl apply -f kubernetes/update-consumer-deployment.yaml

    - name: Rollback on failure
      if: failure()
      run: |
        kubectl rollout undo deployment/gateway-api
        kubectl rollout undo deployment/consulta-api
        kubectl rollout undo deployment/register-consumer
        kubectl rollout undo deployment/update-consumer