name: CI / CD Pipeline

on:
  push:
    branches:
      - main
jobs:
  build_and_test:
    runs-on: ubuntu-latest

    env:
      JWT_Secret: ${{ secrets.JWT_SECRET }}
      RSA_Private: ${{ secrets.RSA_PRIVATE_KEY }}
      RSA_Public: ${{ vars.RSA_PUBLIC_KEY }}
      Solution: ${{ vars.SOLUTION_PATH }}
      Gateway: ${{ vars.GATEWAY_API_PATH }}
      Consulta: ${{ vars.CONSULTA_API_PATH }}
      Register: ${{ vars.REGISTER_CONSUMER_PATH }}
      Update: ${{ vars.UPDATE_CONSUMER_PATH }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.x'

    - name: Restore dependencies
      run: dotnet restore ${{ env.Solution }}

    - name: Build API projects
      run: |
        dotnet build ${{ env.Gateway }} --no-restore --configuration Release
        dotnet build ${{ env.Consulta }} --no-restore --configuration Release

    - name: Build Consumer projects
      run: |
        dotnet build ${{ env.Register }} --no-restore --configuration Release
        dotnet build ${{ env.Update }} --no-restore --configuration Release
